import { PiArrowLeft, PiArrowRight, PiCheck, PiClockCounterClockwise, PiTrendUp, PiX } from "react-icons/pi";
import { COMPARE_BENCHMARKS, stampDate } from "../lib/api.js";
import { ModelMark } from "../components/shared.jsx";

export function Compare({ selected, navigate, toggle, syncDateLabel }) {
  const benchmarks=COMPARE_BENCHMARKS;
  if(selected.length<2) return <section className="page compare-view"><div className="page-hero"><div><p className="eyebrow">MODEL COMPARE</p><h1>模型对比</h1><p>选择 2–5 个明确的 Variant 与 Endpoint，避免混合不同渠道的数据。</p></div></div><div className="panel compare-empty"><span className="empty-icon"><PiTrendUp/></span><h2>{selected.length===1?"再选 1 个模型即可开始":"还没有选择模型"}</h2><p>{selected.length===1?`${selected[0].name} 已加入对比。`:"从模型图谱中选择你真正关心的候选项。"}</p><button className="primary" onClick={()=>navigate("models")}>去选择模型 <PiArrowRight/></button></div></section>;
  return <section className="compare-view page"><button className="text-button" onClick={()=>navigate("models")}><PiArrowLeft/> 返回模型图谱</button><div className="compare-title"><div><p className="eyebrow">最近 3 个月 · 数据截至 {syncDateLabel||"待同步"}</p><h1>模型对比</h1><p>对比明确的模型变体与服务端点，不混合不同渠道数据。</p></div><span className="freshness"><PiClockCounterClockwise/> 90 天窗口</span></div><div className="compare-grid" style={{"--columns":selected.length}}><div className="compare-label blank"/>{selected.map(m=><article className="compare-head" key={m.id}><button onClick={()=>toggle(m.id)} aria-label={`移除 ${m.name}`}><PiX/></button><ModelMark model={m}/><strong>{m.name}</strong><span>{m.variants[0]} · {m.endpoint}</span></article>)}<div className="compare-label">上下文窗口</div>{selected.map(m=><div className="compare-cell" key={`${m.id}-context`}><b>{m.context}</b></div>)}{benchmarks.map(b=><div className="compare-row" key={b}><div className="compare-label">{b}<small>权威评测集</small></div>{selected.map(m=>{const best=Math.max(...selected.map(x=>x.score[b]));return <div className={`compare-cell ${m.score[b]===best?"best":""}`} key={`${m.id}-${b}`}><b>{m.score[b]}</b><span>{m.score[b]===best?"当前最佳":""}</span></div>})}</div>)}<div className="compare-label">来源可信度</div>{selected.map(m=><div className="compare-cell evidence" key={`${m.id}-source`}><PiCheck/><div><b>高</b><span>{m.source} · {stampDate(m.observedAt)||syncDateLabel||"待同步"}</span></div></div>)}</div></section>;
}
